### ISSUE TITLE
Can you complier OCI driver for Qt 6.3 ?

### ISSUE THREAD

**Issue by zaiplanet** [thecodemonkey86/qt_oci_driver#1]

**Comment by thecodemonkey86** [comment]
hi, 
I built the driver for Qt 6.3:  https://github.com/thecodemonkey86/qt_oci_driver/releases/tag/qoci_driver_6.3.0

**Comment by zaiplanet** [comment]
> hi, 
> 
> I built the driver for Qt 6.3:  https://github.com/thecodemonkey86/qt_oci_driver/releases/tag/qoci_driver_6.3.0

Woa, thank you very much :)
You can step by step, how do you complie driver on window or linux?
I tried make it 2 week on windows follow tutorial from https://doc.qt.io/qt-6/sql-driver.html#qoci
 but not complete :(

**Comment by thecodemonkey86** [comment]
I'm not following the Qt docs using CMake, because I couldn't get it to work that way, too. Instead I compiled it using a modified .pro file (originally from Qt5, but still usable for Qt6) which can be loaded and built in Qt Creator, so I can only provide information on this method on Windows. I didn't try to build it on Linux yet

- Download InstantClient SDK package from https://download.oracle.com/otn_software/nt/instantclient/213000/instantclient-sdk-windows.x64-21.3.0.0.0.zip and unzip somewhere
- run git clone of this repo https://github.com/thecodemonkey86/qt_oci_driver.git, switch to branch Qt_6.3
- replace Qt plugin sources from the desired Qt version, eg.  C:\Qt\6.3.0\Src\qtbase\src\plugins\sqldrivers\oci in the directory where the local git repo is located, subfolder oci
- load sqldrivers.pro in Qt Creator
- in oci.pro adjust these paths to InstantClient accordingly: `INCLUDEPATH += D:\Programme\instantclient_21_3\sdk\include
LIBS += -LD:\Programme\instantclient_21_3\sdk\lib\msvc -loci`
- build. If some messages appear about .qmake.conf not being found (since the .pro file is not intended to be used in Qt Creator officially), you can ignore them, as long as the .dll is built

**Comment by zaiplanet** [comment]
> I'm not following the Qt docs using CMake, because I couldn't get it to work that way, too. Instead I compiled it using a modified .pro file (originally from Qt5, but still usable for Qt6) which can be loaded and built in Qt Creator, so I can only provide information on this method on Windows. I didn't try to build it on Linux yet
> 
> 
> 
> - Download InstantClient SDK package from https://download.oracle.com/otn_software/nt/instantclient/213000/instantclient-sdk-windows.x64-21.3.0.0.0.zip and unzip somewhere
> 
> - run git clone of this repo https://github.com/thecodemonkey86/qt_oci_driver.git, switch to branch Qt_6.3
> 
> - replace Qt plugin sources from the desired Qt version, eg.  C:\Qt\6.3.0\Src\qtbase\src\plugins\sqldrivers\oci in the directory where the local git repo is located, subfolder oci
> 
> - load sqldrivers.pro in Qt Creator
> 
> - in oci.pro adjust these paths to InstantClient accordingly: `INCLUDEPATH += D:\Programme\instantclient_21_3\sdk\include
> 
> LIBS += -LD:\Programme\instantclient_21_3\sdk\lib\msvc -loci`
> 
> - build. If some messages appear about .qmake.conf not being found (since the .pro file is not intended to be used in Qt Creator officially), you can ignore them, as long as the .dll is built
> 
> 

Thank you very much. I will try again

**Comment by mitikawa** [comment]
> I'm not following the Qt docs using CMake, because I couldn't get it to work that way, too. Instead I compiled it using a modified .pro file (originally from Qt5, but still usable for Qt6) which can be loaded and built in Qt Creator, so I can only provide information on this method on Windows. I didn't try to build it on Linux yet
> 
>     * Download InstantClient SDK package from https://download.oracle.com/otn_software/nt/instantclient/213000/instantclient-sdk-windows.x64-21.3.0.0.0.zip and unzip somewhere
> 
>     * run git clone of this repo https://github.com/thecodemonkey86/qt_oci_driver.git, switch to branch Qt_6.3
> 
>     * replace Qt plugin sources from the desired Qt version, eg.  C:\Qt\6.3.0\Src\qtbase\src\plugins\sqldrivers\oci in the directory where the local git repo is located, subfolder oci
> 
>     * load sqldrivers.pro in Qt Creator
> 
>     * in oci.pro adjust these paths to InstantClient accordingly: `INCLUDEPATH += D:\Programme\instantclient_21_3\sdk\include LIBS += -LD:\Programme\instantclient_21_3\sdk\lib\msvc -loci`
> 
>     * build. If some messages appear about .qmake.conf not being found (since the .pro file is not intended to be used in Qt Creator officially), you can ignore them, as long as the .dll is built

I can't believe it. It works. I managed to create my own for 5.15.2 x32. Hours and hours of staring at a brick wall written driver not loaded. Thanks a lot, great job !!!
